#Version of the ROM
CHOOSE_REVISION := CHOOSE-10.0

ifndef CHOOSE_BUILDTYPE
    CHOOSE_BUILDTYPE := HOMEMADE
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst choose_,,$(TARGET_PRODUCT_SHORT))

CHOOSE_VERSION := $(CHOOSE_REVISION)-$(CHOOSE_BUILDTYPE)-$(TARGET_PRODUCT_SHORT)-$(shell date -u +%Y%m%d-%H%M)

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(BUILD_USERNAME)@$(BUILD_HOSTNAME)"
