#Version of the ROM
CHOOSE_REVISION := 10.0

ifndef CHOOSE_BUILDTYPE
    CHOOSE_BUILDTYPE := HOMEMADE
endif

TARGET_PRODUCT_SHORT := $(TARGET_PRODUCT)
TARGET_PRODUCT_SHORT := $(subst choose_,,$(TARGET_PRODUCT_SHORT))

CHOOSE_VERSION := $(CHOOSE_REVISION)-$(shell date +%Y%m%d-%H%M)-$(TARGET_PRODUCT_SHORT)-$(CHOOSE_BUILDTYPE)

PRODUCT_BUILD_PROP_OVERRIDES += BUILD_DISPLAY_ID="$(BUILD_ID)-$(BUILD_USERNAME)@$(BUILD_HOSTNAME)"
